name: Node deploy

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  node-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # สำคัญสำหรับการตรวจสอบไฟล์ที่เปลี่ยนแปลง

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.10.0'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci --force

    - name: Build project
      run: npm run build
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}

    # - name: Determine analysis type
    #   id: analysis-type
    #   run: |
    #     # ตรวจสอบว่าเป็น commit แรกหรือไม่
    #     if git log --oneline -1 --skip=1 > /dev/null 2>&1; then
    #       echo "type=incremental" >> $GITHUB_OUTPUT
    #       echo "::notice::Incremental analysis (changed files only)"
    #     else
    #       echo "type=full" >> $GITHUB_OUTPUT
    #       echo "::notice::Full project analysis (first run)"
    #     fi

    # - name: Get changed files for incremental analysis
    #   if: steps.analysis-type.outputs.type == 'incremental'
    #   id: changed-files
    #   uses: tj-actions/changed-files@v41
    #   with:
    #     since_last_remote_commit: 'true'
    #     files: |
    #       **/*.ts
    #       **/*.tsx
    #       **/*.js
    #       **/*.jsx
    #       **/*.json

    # - name: SonarQube Full Analysis (First Run)
    #   if: steps.analysis-type.outputs.type == 'full'
    #   uses: SonarSource/sonarqube-scan-action@v4
    #   env:
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    #   with:
    #     args: >
    #       -Dsonar.projectKey=next-pipeline
    #       -Dsonar.projectName="next-pipeline - Next.js"
    #       -Dsonar.exclusions=**/.next/**,**/node_modules/**
    #       -Dsonar.inclusions=**/*.ts,**/*.tsx

    # - name: SonarQube Incremental Analysis (Subsequent Runs)
    #   if: steps.analysis-type.outputs.type == 'incremental'
    #   uses: SonarSource/sonarqube-scan-action@v4
    #   env:
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    #   with:
    #     args: >
    #       -Dsonar.projectKey=next-pipeline
    #       -Dsonar.projectName="next-pipeline - Next.js"
    #       -Dsonar.exclusions=**/.next/**,**/node_modules/**
    #       -Dsonar.inclusions=**/*.ts,**/*.tsx

  # robot-tests:
  #   needs: sonarqube
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout robot-rem repository
  #       uses: actions/checkout@v4
  #       with:
  #         repository: k0msak007/robot-rem
  #         path: robot-rem
  #         token: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.11'

  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r robot-rem/requirements.txt

  #     - name: Run Robot Framework tests (headless)
  #       run: |
  #         cd robot-rem
  #         robot ./tests